# Generated by Django 3.1.3 on 2021-01-03 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnb_faucet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tnb_faucet',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='tnb_faucet',
            name='next_valid_access_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 4, 1, 22, 44, 239226)),
        ),
    ]
