# Generated by Django 3.1.3 on 2020-12-31 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionlog',
            name='status',
            field=models.CharField(choices=[('UNCONFIRMED', '0'), ('CONFIRMED', '1'), ('REJECTED', '2')], default=0, max_length=11),
        ),
    ]
